---
title: "About the Report"
subtitle: "Description of the 2024 Alaska Electricity Trends Report Web Book"
date-modified: "2024-03-26T14:36:00-08:00"
date-format: "MMM D, YYYY [at] HH:mm z"
---

The Alaska Electrical Trends Report (AETR) Web Book has been produced by the Alaska Center for Energy and Power ([ACEP](https://www.uaf.edu/acep/)) at the University of Alaska Fairbanks ([UAF](https://www.uaf.edu/uaf/index.php)). It is designed to be interactive and dynamically updated when new data becomes available. 

## Historical Timeline of Prior Reports

Throughout the years, several agencies have prepared and published reports and data compilations on energy use in Alaska. AETR is complimentary to those prior reports, but is not a direct successor to them because it focuses on electricity only. Here is a timeline of prior reports for context:

- Before 1985: federal Alaska Power Administration published Alaska Electric Power Statistics report (AEPS)
- 1985: Alaska Energy Authority (AEA, formerly Alaska Power Authority) begins gathering statistical data and publishing annual report
- 1988: AEPS report becomes combined effort of the Alaska Systems Coordinating Council (ASCC) and AEA
- 1993: AEPS becomes joint effort of the ASCC and the Alaska Department of Community and Regional Affairs, Division of Energy
- 1995 - 2003: No reports published
- 2003: the Institute of Social and Economic Research (ISER) at the University of Alaska Anchorage (UAA) prepare a report with funding from AEA, the Regulatory Commission of Alaska (RCA), and the Denali Commission
- 2008 - 2011: ISER prepares Alaska Energy Statistics updates with funding from AEA
- 2012 - 2013: AEA prepares Excel workbook with updated data


## Technical Details

The book is formatted using [Quarto](https://quarto.org), an open-source scientific and technical publishing system. The template was developed by the Openscapes project, as part of their [Quarto Website Tutorial](https://github.com/Openscapes/quarto-website-tutorial).

The markdown files that make up the book reside in the [aetr-web-book](https://github.com/acep-uaf/aetr-web-book) GitHub repository. The generation process is publicly accessible. Errors in the document can be flagged using GitHub issues where they can be tracked and addressed by the DCM team.

The book also integrates R code for data processing and figure generation. When data files are updated, manually triggering the Quarto render will update the figures automatically.
