---
title: "Conclusions"
subtitle: "Description of Results and Conclusions"
date-modified: "2024-04-05T12:45:00-08:00"
date-format: "MMM D, YYYY [at] HH:mm z"
---

&nbsp;


From 2011 to 2019/21, there have been significant developments in the electricity generation landscape in Alaska. In this report, we highlight trends across installed capacity, net/gross generation, consumption by customer class, and price per kWh. There are several key takeaways from each of these areas that we reiterate in this conclusion.

### Capacity

There has been continued development in the installation and availability of electric generation capacity (@sec-capacity) across the state. Throughout every region, installed capacity increased. Of particular note are the installation of peaking and/or backup engines, renewable energy facilities (hydro, wind, and solar expansions), and storage. If trends continue, we can expect to see further increases in resilience and reliability-focused capacity.

### Generation

Net/gross generation (@sec-generation) throughout the state remained relatively stable across observed years with each region having notable trends. In the Coastal region, we observed more hydroelectric and wind generation on average in 2021 than in 2011. This was coupled with reductions in generation from oil-based units. On the Railbelt, we observed more generation from wind, hydroelectric, coal, and solar resources in 2021 than in 2011. This was coupled with less oil and natural gas generation. Finally, in the Rural Remote region, we observed more generation from wind and solar resources in 2021 than in 2011. We also note the increase in use of utility-scale battery storage throughout the state. 

### Consumption

Electricity consumption (@sec-consumption) throughout the state fell on average. The residential customer class saw the largest reductions, while the number of customer accounts increased across all categories. We also note that the Rural Remote region saw increases in consumption for the commercial and industrial customer classes. Finally, we observed that the Coastal region had the highest per capita consumption for residential customers, followed by the Railbelt and then the Rural Remote regions.

### Prices

Electricity prices (@sec-prices) across the state were variable but trended upward. After adjusting for inflation, PCE subsidies, and including a population weight, the average residential electricity price across the state increased. The largest residential rate increases from 2011 to 2019 were observed in the Railbelt region (26%), and the smallest were observed in the Coastal region (6%). Throughout the Coastal and Rural Remote regions, commercial and other customer classes saw rate decreases. Rate decreases were also observed on the Railbelt for commercial customers. We also observed that PCE subsidies were paramount to mitigating the cost of electricity for residential and community customers in the Rural Remote and Coastal regions.

## Future Plans

The results of this trends report highlight the direction that installed capacity, net/gross generation, consumption, and prices took from 2011-2019/21. We emphasize the importance of continuing to collate electricity data from federal, state, regional, and local sources so that it may be analyzed on a more consistent basis. Our hope is to continue producing trends reports with updated data to better inform the public and decision makers regarding Alaska's energy future.