---
title: "Net/Gross Generation"
subtitle: "Generation by Fuel Type in Alaska, 2011-2021"
date-modified: "2024-04-11T09:11:00-08:00"
date-format: "MMM D, YYYY [at] HH:mm z"
output:
  quarto::quarto_html:
    pre_processor: quarto::observable
cap-location: top
echo: false
---

```{r, echo=FALSE,warning=FALSE,message=FALSE}
# Import required packages
library(tidyr)
library(dplyr)
library(readr)

# Import the data
generation_data <- read.csv(file = "data/final_data/generation.csv")

# Regional totals
regional_generation_data <- generation_data %>%
  group_by(acep_region, year) %>%
  summarize(
    "total_gen" = sum(generation, na.rm = TRUE)
  ) %>%
  mutate(
    total_gen = total_gen / 1000
  )

# Regional generation mixes
regional_generation_mix <- generation_data %>%
  group_by(acep_region, year, fuel_type) %>%
  summarize(
    generation = sum(generation, na.rm=TRUE)
  ) %>%
  filter(fuel_type != "Storage") %>%
  group_by(acep_region, year) %>%
  mutate(
    total_generation = sum(generation,na.rm=TRUE)
  ) %>%
  group_by(acep_region,year,fuel_type) %>%
  mutate(
    gen_share = ((generation / total_generation)*100)
  )

# Function declarations
source("scripts/inline_functions/generation_inline_functions.R")
```

## General Overview {#sec-generation}

This section outlines the trends in generation by fuel type for each region. Generation in our context has two separate definitions. Data collected through the Energy Information Administration (EIA) records "net" generation, which excludes electricity use for power plant operations.[^1] However, data collected from the Alaska Energy Authority's (AEA) Power Cost Equalization (PCE) program is presented as "gross" generation, which does not make this exclusion.[^2]

[^1]: The EIA-923 data used for net generation was supplemented with FERC Form No. 1 data to account for missing statistics for the Southcentral Power Project. Please visit [the patch notes to learn more about our methodology and findings](https://github.com/acep-uaf/aetr-web-book-2024/tree/main/data/patches/patch_001).

[^2]: The PCE data do show powerhouse consumption as a separate data item, which would allow for the computation of "net generation" in PCE communities. However, we have continued to report generation in PCE communities as the gross amount in order to be consistent with previous Alaska Energy Statistics Reports.

@fig-generation-by-region provides a visual representation of yearly electricity generation for the Coastal, Railbelt, and Rural Remote regions. All regions produced a relatively consistent amount of electricity between 2011 and 2021. Across this time period, the Railbelt generated an average of `r regional_generation("Railbelt")` GWh, the Coastal region generated an average of `r regional_generation("Coastal")` GWh, and the Rural Remote region generated an average of `r regional_generation("Rural Remote")` GWh. Between 2011 and 2021, the average yearly growth rate for generation was `r cagr("Coastal")`% in the Coastal region, `r cagr("Railbelt")`% in the Railbelt region, and `r cagr("Rural Remote")`% in Rural Remote communities.[^3] The Coastal and Rural Remote trends are in line with improvements in rural electrification, as well as modest population growth. Of the regions, the Railbelt is the only one that consistently saw decreases in generation across the years. Total statewide generation increased at an average annual growth rate of 0.22%.

[^3]: Calculated with the compound average growth rate: $CAGR = \left(\left(\frac{gen_{2021}}{gen_{2011}} \right)^{\frac{1}{2021-2011}} -1\right)$

```{ojs}
//| echo: false
import {tidy, groupBy, rename, summarize, sum, mutate, select, n, nDistinct, mean, filter, pivotWider, pivotLonger, leftJoin, slice, fullJoin, lag, TMath, rowNumber,mutateWithSummary} from "@pbeshai/tidyjs"

// Import the long-form generation data
gen_data = FileAttachment("data/final_data/generation.csv").csv({ typed: true })

// Convert MWh to GWh
gen_data_gwh = tidy(gen_data, mutate({
  generation: (d) => d.generation / 1000
})).map((d) => ({...d, "Fuel Type": d.fuel_type})).map((d) => ({...d, "ACEP Region": d.acep_region}));

//gen_data_gwh = gen_data_gwh_.map((d) => ({...d, "ACEP Region": d.acep_region},{...d, "Fuel Type": d.fuel_type}))

```

```{ojs}
//| label: fig-generation-by-region
//| fig-cap: "Electricity Generation by Region"

// Plotting total generation by region and year//| 
Plot.plot({
  
  // Configure the plot
  //title: " Electricity generation by region",
  insetLeft: 0,
  insetRight: 0,
  width: width,
  
  // Configure the x-axis
  x: {
    tickFormat: "d",
    label: "Year"
  },
  
  // Configure the y-axis
  y: {
    grid: true,
    label: "Generation (GWh)"
  },
  
  // Plotting the series
  marks: [
    Plot.barY(
      gen_data_gwh,
      Plot.groupX(
        {
          y: "sum"
        },
        {
          x: "year",
          y: "generation",
          fill: "ACEP Region",
          tip: {format: {x: "d"}}
        }
      )
    ),
    Plot.ruleY([0])
  ],
  
  // Legend
  color: {
    domain: ["Coastal","Railbelt","Rural Remote"],
    range: ["#8cbbda","#97cd93","#f28d8c"],
    legend: true
  }
})
```

While generation did not change significantly during the observed time period, the resources from which generation occurred, did. @fig-generation-changes-by-region shows how the mix of generation fuels changed between 2011 and 2021.[^4]

[^4]: Oil consists of generators whose primary fuel source is diesel/distillate, naphtha, or jet fuel. Gas consists of natural or landfill gas. Hydro refers to conventional hydroelectric turbines. Wind and solar are both utility-scale (excluding behind-the-meter solar). Storage is not included in these calculations.

```{ojs}
//| echo: false

// Establish the figure caption for generation mix charts
caption_gen_mix = "Note: Storage is not included here due since net generation is negative."

// Creating a modified version of the data
share_data = tidy(
  gen_data,
  groupBy(
    ['year','acep_region','fuel_type'], 
    [
      summarize({
        generation: sum('generation')
      })
    ]
  )
)

// Creating total generation data from each region and year
total_gen = tidy(share_data, groupBy(['year','acep_region'], summarize({total_generation: sum('generation')})))


// Creating a joined table from the above two
join = tidy(share_data, fullJoin(total_gen, {by: ['year','acep_region']}))

// Creating a column with shares
join_shares = tidy(join.filter((d) => d.fuel_type !== "Storage"),
  mutate({generation_share: (d) => (d.generation / d.total_generation)*100})
).map((d) => ({...d, "Fuel Type": d.fuel_type})).map((d) => ({...d, "ACEP Region": d.acep_region})) // join_shares should be used for the 100% area charts

// Table for just the 2011 and 2021 generation mix comparison
gen_mix_diff = tidy(
  join_shares.filter((d) => d.year === 2011 || d.year === 2021),
  groupBy(
    ['ACEP Region','Fuel Type'],
    mutateWithSummary({
        generation_share_2011: lag('generation_share', {default: 0})
    })
  ),
  mutate({
    delta: (d) => d.generation_share - d.generation_share_2011
  }),
  filter(
    (d)  => d.year === 2021
  )
)
```

```{ojs}
//| label: fig-generation-changes-by-region
//| fig-cap: "Regional Changes in Net Generation"

// Plotting the deltas
Plot.plot({
  //title: "Regional changes in net generation",
  caption: "Percentage point differences in generation mix between 2021 and 2011",
  insetLeft: 15,
  insetRight: 15,
  marginRight: 70,
  height: 600,
  width: width,

  x: {
    label: "Percentage Point Change",
    labelAnchor: "center"
  },

  y: {
    grid: true,
    domain: ["Coal","Oil","Gas","Hydro","Wind","Solar"],
    label: ""
  },

  facet: {
    data: gen_mix_diff,
    y: (d) => d.acep_region
  },

  marks: [
    Plot.frame(),
    Plot.barX(gen_mix_diff, {
        x: "delta",
        y: "Fuel Type",
        fill: "Fuel Type",
        order: ["Coal","Oil","Gas","Hydro","Wind","Solar"],
        tip: {
          format: {
            x: (d) => `${(d).toLocaleString(undefined, {maximumFractionDigits: 2})}%`,
            y: false,
            fy: false
          }
        }
      }
    ),
    Plot.ruleX([0])
  ],

  color: {
    domain: ["Coal","Oil","Gas","Hydro","Wind","Solar"],
    range: ["#7f7f7f","#BFBFBF","#DCD9C5","#96B3DF","#F79646","#F5C243"],
    legend: true
  }
})
```

We show that for these resources, the Coastal region displaced oil generation with hydro and wind generation. The Railbelt displaced gas and oil generation with coal, hydro, and solar generation. Finally, the Rural Remote region of the state displaced coal and a small amount of hydro with gas, solar, and wind generation.

This figure does not include trends in storage or the other category. Storage net generation is always negative due to the efficiency of current battery systems where more energy is sent to storage than can be recovered. The "other" category was not included in this figure as net generation was zero in 2011 and 2021 (but not throughout the series, which we show in the subsequent sections).

## Coastal

In 2011, the Coastal region generated `r generation_share("Coastal",2011,"Hydro")`% of its electricity from hydro, `r generation_share("Coastal",2011,"Oil")`% from oil, and the remainder from wind.[^5] In 2021, the region generated `r generation_share("Coastal",2021,"Hydro")`% of electricity from hydro, `r generation_share("Coastal",2021,"Oil")`% from oil, and `r generation_share("Coastal",2021,"Wind")`% from wind. In addition, storage played a role in generation, albeit the net result is negative due to efficiencies. @fig-generation-fuel-coastal shows how this generation mix has changed over the years.

[^5]: Net generation from storage facilities are not included in these calculations.

```{ojs}
//| label: fig-generation-fuel-coastal
//| fig-cap: "Share of Net Generation by Fuel Type, Coastal Region"

// Plotting the shares for the coastal region
Plot.plot({

  // Configure the plot
  //title: "Share of net generation by fuel type, Coastal region",
  caption: caption_gen_mix,
  insetLeft: 0,
  insetRight: 0,
  width: width,
  
  // Configure the x-axis
  x: {
    tickFormat: "d",
    label: "Year"
  },
  
  // Configure the y-axis
  y: {
    grid: true,
    label: "Share of electricity generation"
  },
  
  marks: [
    Plot.areaY(
      join_shares.filter((d) => d.acep_region === "Coastal"),
      {
        x:"year",
        y:"generation_share", 
        fill: "Fuel Type",
        order: ["Oil","Hydro","Wind"],
        tip: {format: {x: "d", y: (d) => `${(d).toLocaleString(undefined, {maximumFractionDigits: 2})}%`}}
      }
    ),
    Plot.ruleY([0])
  ],
  
  // Legend
  color: {
    domain: ["Oil","Hydro","Wind"],
    range: ["#BFBFBF","#96B3DF","#F79646"],
    legend: true
}
})
```

Generation grew at an average annual growth rate of `r cagr("Coastal")`% from 2011 to 2021. @fig-generation-coastal highlights the yearly trends in generation by fuel source.

```{ojs}
//| label: fig-generation-coastal
//| fig-cap: "Electricity Generation, Coastal Region"

// Plotting total generation by region and year
Plot.plot({
  
  // Configure the plot
  //title: "Coastal region electricity generation",
  insetLeft: 0,
  insetRight: 0,
  width: width,
  
  // Configure the x-axis
  x: {
    tickFormat: "d",
    label: "Year"
  },
  
  // Configure the y-axis
  y: {
    grid: true,
    label: "Generation (GWh)"
  },
  
  // Plotting the series
  marks: [
    Plot.barY(
      gen_data_gwh.filter(d => d.acep_region === "Coastal" && d.generation !== null),
      Plot.groupX(
        {
          y: "sum"
        },
        {
          x: "year",
          y: "generation",
          fill: "Fuel Type",
          order: ["Oil","Hydro","Wind"],
          tip: {format: {x: "d"}}
        }
      )
    ),
    Plot.ruleY([0])
  ],
  
  // Legend
  color: {
    domain: ["Oil","Hydro","Wind"],
    range: ["#BFBFBF","#96B3DF","#F79646"],
    legend: true
  }
})
```

## Railbelt

Railbelt generation has seen notable changes in how it generates electricity between 2011 and 2021. In 2011, the Railbelt region generated `r generation_share("Railbelt",2011,"Gas")`% of electricity from gas, `r generation_share("Railbelt",2011,"Coal")`% from coal, `r generation_share("Railbelt",2011,"Hydro")`% from hydro, and `r generation_share("Railbelt",2011,"Oil")`% from oil. Additionally, a small amount of wind generation was present. In 2021, the region generated `r generation_share("Railbelt",2021,"Gas")`% of electricity from gas, `r generation_share("Railbelt",2021,"Coal")`% from coal, `r generation_share("Railbelt",2021,"Hydro")`% from hydro, `r generation_share("Railbelt",2021,"Oil")`% from oil, and `r generation_share("Railbelt",2021,"Wind")`% from wind. Additionally, a small amount of solar generation was present. In addition, storage played a role in generation, albeit the net result is negative due to non-perfect efficiencies. @fig-generation-fuel-railbelt shows how this generation mix has changed over the years.

```{ojs}
//| label: fig-generation-fuel-railbelt
//| fig-cap: "Share of Net Generation by Fuel Type, Railbelt Region"

Plot.plot({//| 

  // Configure the plot
  //title: "Share of net generation by fuel type, Railbelt region",
  caption: caption_gen_mix,
  insetLeft: 0,
  insetRight: 0,
  width: width,
  
  // Configure the x-axis
  x: {
    tickFormat: "d",
    label: "Year"
  },
  
  // Configure the y-axis
  y: {
    grid: true,
    label: "Share of electricity generation"
  },
  
  marks: [
    Plot.areaY(
      join_shares.filter((d) => d.acep_region === "Railbelt"),
      {
        x:"year",
        y:"generation_share", 
        fill: "Fuel Type",
        order: ["Coal","Oil","Gas","Hydro","Wind","Solar"],
        tip: {format: {x: "d", y: (d) => `${(d).toLocaleString(undefined, {maximumFractionDigits: 2})}%`}}
      }
    ),
    Plot.ruleY([0])
  ],
  
  // Legend
  color: {
    domain: ["Coal","Oil","Gas","Hydro","Wind","Solar"],
    range: ["#7f7f7f","#BFBFBF","#DCD9C5","#96B3DF","#F79646","#F5C243"],
    legend: true
  },
})
```

Generation from 2011 to 2021 saw an average annual growth rate of `r cagr("Railbelt")`%. @fig-generation-railbelt highlights the yearly trends in generation by fuel source.

```{ojs}
//| label: fig-generation-railbelt
//| fig-cap: "Electricity Generation, Railbelt Region"

// Plotting total generation by region and year
Plot.plot({
  
  // Configure the plot
  //title: "Railbelt region electricity generation",
  insetLeft: 0,
  insetRight: 0,
  width: width,
  
  // Configure the x-axis
  x: {
    tickFormat: "d",
    label: "Year"
  },
  
  // Configure the y-axis
  y: {
    grid: true,
    label: "Generation (GWh)"
  },
  
  // Plotting the series
  marks: [
    Plot.barY(
      gen_data_gwh.filter(d => d.acep_region === "Railbelt"),
      Plot.groupX(
        {
          y: "sum"
        },
        {
          x: "year",
          y: "generation",
          fill: "Fuel Type",
          order: ["Coal","Oil","Gas","Hydro","Wind","Solar"],
          tip: {format: {x: "d"}}
        }
      )
    ),
    Plot.ruleY([0])
  ],
  
  // Legend
  color: {
    domain: ["Coal","Oil","Gas","Hydro","Wind","Solar"],
    range: ["#7f7f7f","#BFBFBF","#DCD9C5","#96B3DF","#F79646","#F5C243"],
    legend: true
  }
})
```

## Rural Remote

The Rural Remote region has seen notable changes between 2011 and 2021 in how it generates electricity. In 2011, the region generated `r generation_share("Rural Remote",2011,"Oil")`% of electricity from oil, `r generation_share("Rural Remote",2011,"Gas")`% from gas, `r generation_share("Rural Remote",2011,"Hydro")`% from hydro, and `r generation_share("Rural Remote",2011,"Wind")`% from wind. In 2021, the region generated `r generation_share("Rural Remote",2021,"Oil")`% of electricity from oil (mostly diesel), `r generation_share("Rural Remote",2021,"Gas")`% from gas, `r generation_share("Rural Remote",2021,"Hydro")`% from hydro, and `r generation_share("Rural Remote",2021,"Wind")`% from wind. Additionally, a small amount of solar generation was present. @fig-generation-fuel-rural shows how this generation mix has changed over the years.

```{ojs}
//| label: fig-generation-fuel-rural
//| fig-cap: "Share of Net Generation by Fuel Type, Rural Remote Region"

// Plotting the shares for the coastal region
Plot.plot({

  // Configure the plot
  //title: "Share of net generation by fuel type, Rural Remote region",
  caption: caption_gen_mix,
  insetLeft: 0,
  insetRight: 0,
  width: width,
  
  // Configure the x-axis
  x: {
    tickFormat: "d",
    label: "Year"
  },
  
  // Configure the y-axis
  y: {
    grid: true,
    label: "Share of electricity generation"
  },
  
  marks: [
    Plot.areaY(
      join_shares.filter((d) => d.acep_region === "Rural Remote"),
      {
        x:"year",
        y:"generation_share", 
        fill: "Fuel Type",
        order: ["Oil","Gas","Hydro","Wind","Solar","Other"],
        tip: {format: {x: "d", y: (d) => `${(d).toLocaleString(undefined, {maximumFractionDigits: 2})}%`}}
      }
    ),
    Plot.ruleY([0])
  ],
  
  // Legend
  color: {
    domain: ["Oil","Gas","Hydro","Wind","Solar","Other"],
    range: ["#BFBFBF","#DCD9C5","#96B3DF","#F79646","#F5C243","#C0504D"],
    legend: true
}
})
```

Generation from 2011 to 2021 saw an average annual growth rate of `r cagr("Rural Remote")`%. @fig-generation-rural highlights the yearly trends in generation by fuel source. From 2013 to 2014, a large increase in gas generation is observed due to operations on the North Slope - specifically in the Barrow Utilities & Electric Cooperative, Inc. (BUECI), Deadhorse, and Nuiqsut service regions.

```{ojs}
//| label: fig-generation-rural
//| fig-cap: "Electricity Generation, Rural Remote Region"

// Plotting total generation by region and year
Plot.plot({
  
  // Configure the plot
  //title: "Rural remote region electricity generation",
  insetLeft: 0,
  insetRight: 0,
  width: width,
  
  // Configure the x-axis
  x: {
    tickFormat: "d",
    label: "Year"
  },
  
  // Configure the y-axis
  y: {
    grid: true,
    label: "Generation (GWh)"
  },
  
  // Plotting the series
  marks: [
    Plot.barY(
      gen_data_gwh.filter(d => d.acep_region === "Rural Remote"),
      Plot.groupX(
        {
          y: "sum"
        },
        {
          x: "year",
          y: "generation",
          fill: "Fuel Type",
          order: ["Oil","Gas","Hydro","Wind","Solar","Other"],
          tip: {format: {x: "d"}}
        }
      )
    ),
    Plot.ruleY([0])
  ],
  
  // Legend
  color: {
    domain: ["Oil","Gas","Hydro","Wind","Solar","Other"],
    range: ["#BFBFBF","#DCD9C5","#96B3DF","#F79646","#F5C243","#C0504D"],
    legend: true
  }
})
```
