---
title: "Historical Electric Power Statistics Reports"
subtitle: "Links to Previous Reports, Data Years 1960-2012"
---

```{r, echo=FALSE,warning=FALSE,message=FALSE}

# Function to make space regardless of execution format
# To use: write `r space() outside of a code block
# Modify globally at ./scripts/inline_functions/space.R
source("scripts/R/space.R")

```

`r space(br="", vspace="-3em")`

## Historical Electric Power Reports {#sec-historic-reports}

For an overall description of previous reports that have examined electric power trends in Alaska, please see @sec-historic-timeline. Below is an exhaustive list of links to these reports over time. Notably, we omit reports that include projections such as the State of Alaska Energy Reports/Plans.

<!-- This include was disabled because the table cross reference didn't work correctly with it {{< include _previous_trends_reports.qmd >}} -->

| Publication   Year | Data Years | Data Year Type | Authoring Institution                                                                                                     | Publication Title                                                         | Type                   | Persistent Links                                                                                                                                      |
|:------------------:|:----------:|:--------------:|--------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------|------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------|
|        1969        |    1968    |     Fiscal     | United States Department of the Interior, Alaska Power Administration                                                    | First Annual Report                                                       | Report                 | [First Annual   Report](https://aealibrary.org/WebLink/DocView.aspx?id=37972&dbid=0&repo=AEA)                                                         |
|        1971        |  1960-1969 |    Calendar    | United States Department of the Interior, Alaska Power Administration                                                    | Alaska Electric Power Statistics 1960 - 1969                              | Report                 | [Alaska Electric Power Statistics 1960 -   1969](https://aealibrary.org/WebLink/DocView.aspx?id=36948&dbid=0&repo=AEA)                                |
|        1972        |  1960-1970 |    Calendar    | United States Department of the Interior, Alaska Power Administration                                                    | Alaska Electric Power Statistics 1960 - 1970                              | Report                 | [Alaska Electric Power Statistics 1960 -   1970](https://aealibrary.org/WebLink/DocView.aspx?id=36942&dbid=0&repo=AEA)                                |
|        1974        |  1960-1973 |    Calendar    | United States Department of the Interior, Alaska Power Administration                                                    | Alaska Electric Power Statistics 1960 - 1973                              | Report                 | [Alaska Electric Power Statistics 1960 -   1973](https://aealibrary.org/WebLink/DocView.aspx?id=36927&dbid=0&repo=AEA)                                |
|        1976        |  1960-1975 |    Calendar    | United States Department of the Interior, Alaska Power Administration                                                    | Alaska Electric Power Statistics 1960 - 1975                              | Report                 | [Alaska Electric Power Statistics 1960 -   1975](https://aealibrary.org/WebLink/DocView.aspx?id=36916&dbid=0&repo=AEA)                                |
|        1977        |  1960-1976 |    Calendar    | United States Department of the Interior, Alaska Power Administration                                                    | Alaska Electric Power Statistics 1960 - 1976                              | Report                 | [Alaska Electric Power Statistics 1960 -   1976](https://aealibrary.org/WebLink/DocView.aspx?id=36934&dbid=0&repo=AEA)                                |
|        1981        |  1960-1980 |    Calendar    | United States Department of Energy, Alaska Power Administration                                                          | Alaska Electric Power Statistics 1960 - 1980                              | Report                 | [Alaska Electric Power Statistics 1960 -   1980](https://aealibrary.org/WebLink/DocView.aspx?id=36882&dbid=0&repo=AEA)                                |
|        1983        |  1960-1982 |    Calendar    | United States Department of Energy, Alaska Power Administration                                                          | Alaska Electric Power Statistics 1960 - 1982                              | Report                 | [Alaska Electric Power Statistics 1960 -   1982](https://aealibrary.org/WebLink/DocView.aspx?id=36869&dbid=0&repo=AEA)                                |
|        1984        |  1960-1983 |    Calendar    | State of Alaska, Alaska Power Authority                                                                                  | Alaska Electric Power Statistics 1960 - 1983                              | Report                 | [Alaska Electric Power Statistics 1960 -   1983](https://aealibrary.org/WebLink/DocView.aspx?id=36861&dbid=0&repo=AEA)                                |
|        1985        |  1960-1984 |    Calendar    | State of Alaska, Alaska Power Authority                                                                                  | Alaska Electric Power Statistics 1960 - 1984                              | Report                 | [Alaska Electric Power Statistics 1960 -   1984](https://aealibrary.org/WebLink/DocView.aspx?id=36836&dbid=0&repo=AEA)                                |
|        1986        |  1960-1985 |    Calendar    | State of Alaska, Alaska Power Authority                                                                                  | Alaska Electric Power Statistics 1960 - 1985                              | Report                 | [Alaska Electric Power Statistics 1960 -   1985](https://aealibrary.org/WebLink/DocView.aspx?id=36835&dbid=0&repo=AEA)                                |
|        1987        |  1960-1986 |    Calendar    | State of Alaska, Alaska Power Authority                                                                                  | Alaska Electric Power Statistics 1960 - 1986                              | Report                 | [Alaska Electric Power Statistics 1960 -   1986](https://aealibrary.org/WebLink/DocView.aspx?id=36831&dbid=0&repo=AEA)                                |
|        1988        |  1960-1987 |    Calendar    | State of Alaska, Alaska Power Authority                                                                                  | Alaska Electric Power Statistics 1960 - 1987                              | Report                 | [Alaska Electric Power Statistics 1960 -   1987](https://aealibrary.org/WebLink/DocView.aspx?id=36828&dbid=0&repo=AEA)                                |
|        1989        |  1960-1988 |    Calendar    | State of Alaska, Alaska Energy    Authority                                                                              | Alaska Electric Power Statistics 1960 - 1988                              | Report                 | [Alaska Electric Power Statistics 1960 -   1988](https://aealibrary.org/WebLink/DocView.aspx?id=36667&dbid=0&repo=AEA)                                |
|        1990        |  1960-1989 |    Calendar    | State of Alaska, Alaska Energy    Authority                                                                              | Alaska Electric Power Statistics 1960 - 1989                              | Report                 | [Alaska Electric Power Statistics 1960 -   1989](https://aealibrary.org/WebLink/DocView.aspx?id=36663&dbid=0&repo=AEA)                                |
|        1991        |  1960-1990 |    Calendar    | State of Alaska, Alaska Energy    Authority                                                                              | Alaska Electric Power Statistics 1960 - 1990                              | Report                 | [Alaska Electric Power Statistics 1960 -   1990](https://aealibrary.org/WebLink/DocView.aspx?id=36658&dbid=0&repo=AEA)                                |
|        1992        |  1960-1991 |    Calendar    | State of Alaska, Alaska Energy    Authority                                                                              | Alaska Electric Power Statistics 1960 - 1991                              | Report                 | [Alaska Electric Power Statistics 1960 -   1991](https://aealibrary.org/WebLink/DocView.aspx?id=36657&dbid=0&repo=AEA)                                |
|        1993        |  1960-1992 |    Calendar    | Alaska Systems Coordinating Council; State of Alaska, Department of   Community and Regional Affairs, Division of Energy | Alaska Electric Power Statistics 1960 - 1992                              | Report                 | [Alaska Electric Power Statistics 1960 -   1992](https://aealibrary.org/WebLink/DocView.aspx?id=36656&dbid=0&repo=AEA)                                |
|        1994        |  1960-1993 |    Calendar    | Alaska Systems Coordinating Council; State of Alaska, Department of   Community and Regional Affairs, Division of Energy | Alaska Electric Power Statistics 1960 - 1993                              | Report                 | [Alaska Electric Power Statistics 1960 -   1993](https://aealibrary.org/WebLink/DocView.aspx?id=36655&dbid=0&repo=AEA)                                |
|        1995        |  1960-1994 |    Calendar    | Alaska Systems Coordinating Council; State of Alaska, Department of   Community and Regional Affairs, Division of Energy | Alaska Electric Power Statistics 1960 - 1994                              | Report                 | [Alaska Electric Power Statistics 1960 -   1994](https://aealibrary.org/WebLink/DocView.aspx?id=36651&dbid=0&repo=AEA)                                |
|        1996        |  1960-1995 |    Calendar    | Alaska Systems Coordinating Council; State of Alaska, Department of   Community and Regional Affairs, Division of Energy | Alaska Electric Power Statistics 1960 - 1995                              | Report                 | [Alaska Electric Power Statistics 1960 -   1995](https://aealibrary.org/WebLink/DocView.aspx?id=36650&dbid=0&repo=AEA)                                |
|        2003        |  1960-2001 |    Calendar    | University of Alaska Anchorage, Institute of Social and Economic Research                                                | Alaska Electric Power Statistics (with Alaska Energy Balance) 1960 - 2001 | Report                 | [Alaska Electric Power Statistics (with   Alaska Energy Balance) 1960 -   2001](https://aealibrary.org/WebLink/DocView.aspx?id=36646&dbid=0&repo=AEA) |
|        2011        |  1960-2008 |    Calendar    | University of Alaska Anchorage, Institute of Social and Economic Research                                                | Alaska Energy Statistics 1960 - 2008                                      | Report, Excel Workbook | [Alaska Energy Statistics 1960 -   2008](http://hdl.handle.net/11122/4134)                                                                            |
|        2011        |  1960-2009 |    Calendar    | University of Alaska Anchorage, Institute of Social and Economic Research                                                | Alaska Energy Statistics 1960 - 2009                                      | Report, Excel Workbook | [Alaska Energy Statistics 1960 -   2009](http://hdl.handle.net/11122/4069)                                                                            |
|        2012        |  1960-2010 |    Calendar    | University of Alaska Anchorage, Institute of Social and Economic Research                                                | Alaska Energy Statistics 1960 - 2010 Final Report                         | Report, Excel Workbook | [Alaska Energy Statistics 1960 - 2010   Final Report](http://hdl.handle.net/11122/3924)                                                               |
|        2013        |  1960-2011 |    Calendar    | University of Alaska Anchorage, Institute of Social and Economic Research                                                | Alaska Energy Statistics 1960 - 2011 Final Report                         | Report, Excel Workbook | [Alaska Energy Statistics 1960 - 2011   Final Report](http://hdl.handle.net/11122/3852)                                                               |
|        2015        |    2012    |    Calendar    | State of Alaska, Alaska Energy Authority                                                                                 | 2012 Alaska Energy Statistics Final Report                                | Report                 | [2012 Alaska Energy Statistics Final   Report](https://aealibrary.org/WebLink/DocView.aspx?id=461&dbid=0&repo=AEA)                                    |
:  Links to Historical Reports {#tbl-historic-reports .striped}
