---
title: "Alaska Electricity Trends Web Book"
subtitle: "Analysis of Alaska Electricity Data, 2011-2021"
---

## Welcome  {#welcome}

This interactive report summarizes federal, state, and utility data in the form of a web book. It provides an overview of electricity capacity, generation, consumption, and price trends from 2011 to 2021. A comprehensive report highlighting these trends has not been produced for the state of Alaska since the 2013 Alaska Energy Statistics Report.

The book has been designed to be a living document that will be updated as more data becomes available. Please explore the data using the chapter navigation links in the left sidebar and the section navigation links in the right sidebar. Additional chapters include:

- About the Report: an historical timeline of previous Alaskan energy reports and technical details on this version.
- About the Team: credits and acknowledgments for the people and funding sources that contributed to this report.

## Executive Summary

The objective of this work is to provide regulators, legislators, and other energy stakeholders with a holistic look at recent trends in electrical generation. The first impetus for this report is a lack of combined reporting on electricity generation across the state that extends to federally and non-federally regulated electric utilities. The second impetus for this report is to aid in decision-making processes surrounding Alaska's energy future.

With uncertainty in natural gas sources on the Railbelt, changing technology, and lower-cost alternatives, understanding trends in the state's capacity, generation, consumption, and prices is vital to more informed decision-making.

In this report, we present data collected from federal, state, and local sources supplemented by correspondence with utilities. We show trends for capacity, generation, consumption, and prices. The capacity and generation trends include data from 2011 to 2021, and the consumption and prices trends are data limited to 2019. More information on sources and methods are provided in the subsequent sections throughout the report. This report uses data visualizations as the primary mode for presenting the trends. To accommodate this presentation style, we present trends as simplified regions of the state as opposed to the Alaska Energy Authority energy regions.

We emphasize that this report is designed to provide factual information to the best of our ability without providing recommendations or in-depth analysis. However, context is provided for more impactful trends.


## Key Takeaways

### Capacity
- Generation capacity on average increased across all of Alaska from 2011 to 2021.
- The state saw large increases in renewable energy capacity, storage, and on-demand peaking units.

### Generation
- Net generation has remained relatively stable
- The Coastal region generated more power from wind and hydro, but less from oil in 2021 than in 2011.
- The Railbelt region generated more power from wind, hydro, coal, and solar, but less from oil and gas in 2021 than in 2011.
- The Rural Remote region generated more power from wind and solar, but less from oil and hydro in 2021 than in 2011.
- We have seen significant increases in the usage of utility-scale battery storage.

### Consumption
- Electricity consumption has fallen for all customer classes, with residential customers seeing the most reductions.
- The number of customer accounts have continued to increase throughout the state.
- Per capita consumption for the residential sector is highest in the Coastal region and lowest in the Rural Remote region.

### Prices
- Residential electricity rates increased on average across Alaska after adjusting for inflation, the PCE subsidy, and population weighting.
- The region that experienced the least residential rate gain was the Coastal region with a 6% increase.
- The region experiencing the highest residential rate gain was the Railbelt with a 26% increase.
- Commercial and Other customers in the Coastal and Rural Remote regions saw rate decreases where Commercial customers in the Railbelt region saw price increases of about 15%.
- PCE subsidies continue to dampen residential prices in the Coastal and Rural Remote regions.




