---
title: "Price of Electricity"
subtitle: "Electricity Prices for the Residential, Commercial, and Industrial Customer Classes, 2011-2019"
date-modified: "2024-04-08T11:48:00-08:00"
date-format: "MMM D, YYYY [at] HH:mm z"
output:
  quarto::quarto_html:
    pre_processor: quarto::observable
cap-location: top
echo: false
---

## General Overview  {#sec-prices}

Utilities in Alaska serve multiple customers, namely residential, commercial, industrial, government/municipal, and community customer classes. Each customer class experiences a different set of costs such as per kWh charge as well as monthly customer charges. In this section, we aim to highlight trends in electricity prices for the residential, commercial, and other customer classes across the Coastal, Railbelt, and Rural Remote regions. We again restrict the data years in this section to 2011 to 2019 due to concerns with data validity for 2020-21.

In rural areas, many communities are eligible to participate in the PCE program (described in @sec-pce-description). It is important to note that the prices presented here reflect the post-PCE adjustment and are annualized averages based on the calendar year. Yearly average effective rates listed here reflect the calendar year and not the fiscal year, which will make them different from those reported in the AEA’s annual reports. We also note that for PCE communities, the rates are reported in the original data. For data sourced from the EIA, rates were calculated by dividing total revenue by total kWh sold in each customer class - this may overestimate the rate as this would include revenue from customer charges.

Note that all prices in this section have been adjusted for inflation over time to 2021 dollars using the Bureau of Labor Statistics (BLS) Consumer Price Index (CPI) for all items in urban Alaska (BLS CUUSA427SA0). To our knowledge, there is no CPI that properly accounts for price changes over time in rural Alaska. However, the general trend shows that customer account-weighted prices have been relatively stagnant across all regions of the state.


### Regional Overview
@fig-price-regions-classes shows the distribution of prices across a selected customer class. The three classes used in this analysis can be selected from the dropdown menu. Hover your pointer over the dot to display utility information.  

Most notably, the dramatic effects of the PCE subsidy can be seen by comparing the price distribution of the residential customer class against the price distribution of the commercial/other customer classes in the Rural Remote and Coastal regions. 


<!--<br> -->

 {{< include _prices_raincloud.qmd >}}


<br>


### Regional Averages
Due to the wide range of electricity prices in Alaska, it is difficult to accurately summarize the data. Because of this, we determined that averages were best calculated using a customer account weighted average. Population is roughly correlated to price, with small communities experiencing higher rates than larger communities. The average number of customer accounts for the year was used to calculate the weighted arithmetic mean price for each year and region. @fig-price-over-time is a graph of residential customer prices over time using population-weighted averages.  

```{ojs}
// aggregate
region_weighted_prices = tidy(weighted_prices, 
                              groupBy(['acep_energy_region', 'year'], [
                                summarize({ mean_weighted_price: mean('weighted_price')})
                              ]),
                              filter((d) => d.year < 2020)).map((d) => ({...d, "ACEP Region": d.acep_energy_region}))
```
 
```{ojs}
//| label: fig-price-over-time
//| fig-cap: "Residential Price Over Time"

// plot of regional average prices
Plot.plot({

    // Configure the x-axis
    x: {
      domain: [2011, 2019],
      tickFormat: "d",
      label: "Year"
    },
    
    // Configure the y-axis
    y: {
      domain: [10, 60],
      ticks: 6,
      label: "Cents per Kilowatt Hour"
    },
    
    // Configure the plot
    grid: true,
    marginRight: 70,
    height: 600,
  width: width,
  
    marks: [
        Plot.line(region_weighted_prices,
                    {x: "year", 
                    y: "mean_weighted_price",
                    strokeWidth: 5,
                    stroke: "ACEP Region",
                    tip: {format: {x: "d", stroke: false}}
        }),
    Plot.text(region_weighted_prices, 
      Plot.selectLast(
        {x: "year", 
        y: "mean_weighted_price", 
        z: "ACEP Region",
        text: "ACEP Region", 
        frameAnchor: "bottom", 
        dy: -5,
        dx: 25
        }))
    ],
    color: {
        domain: ["Coastal", "Railbelt", "Rural Remote"],
        range: ["#8CBBDA", "#97CD93", "#F28D8C"]
    }
});


```


## Coastal

@fig-price-sector-coastal shows the average price of electricity in the Coastal region for each customer class and year. Between 2011 and 2019, the region experienced decreasing prices for Commercial and Other customers, while Residential customers have seen a slight increase in price.

The average real price (in 2021 dollars) of electricity for Residential customers in the Coastal region rose `{ojs} coastal_res_change`% from `{ojs} coastal_res_2011` cents/kWh in 2011 to `{ojs} coastal_res_2019` cents/kWh in 2019. The average price of electricity for Commercial customers in the Coastal region fell `{ojs} coastal_com_change`% from `{ojs} coastal_com_2011` cents/kWh in 2011 to `{ojs} coastal_com_2019` cents/kWh in 2019. Finally, the average price of electricity for Other customers in the Coastal region fell `{ojs} coastal_other_change`% from `{ojs} coastal_other_2011` cents/kWh in 2011 to `{ojs} coastal_other_2019` cents/kWh in 2019.  

Residential customers in the Coastal region saw increases in the price of electricity while commercial and other customers saw decreases. However, the residential customer class continues to pay the lowest per kWh in the region due to a combination of low prices in high population areas and PCE subsidies in eligible communities.

```{ojs}
// aggregate
coastal_weighted_prices = tidy(weighted_prices, 
                              filter((d) => d.acep_energy_region === "Coastal"),
                              filter((d) => d.year < 2020)
                            ).map((d) => ({...d, "Customer Class": d.sector}))
```

```{ojs}
//| label: fig-price-sector-coastal
//| fig-cap: "Sector Price Over Time, Coastal Region"

// plot of regional average prices
Plot.plot({
    
    // Configure the x-axis
    x: {
      domain: [2011, 2019],
      label: "Year",
      tickFormat: "d"
    },
    
    // Configure the y-axis
    y: {
      domain: [10, 40],
      ticks: 4,
      label: "Cents per Kilowatt Hour"
    },
    
    // Configure the plot
    grid: true,
    marginRight: 70,
  width: width,
  
  
    marks: [

    Plot.line(coastal_weighted_prices,
        {x: "year", 
        y: "weighted_price",
        strokeWidth: 5,
        stroke: "Customer Class",
        tip: {format: {x: "d"}}
        }),
    Plot.text(coastal_weighted_prices, 
      Plot.selectLast(
        {x: "year", 
        y: "weighted_price", 
        z: "Customer Class",
        text: "Customer Class", 
        frameAnchor: "bottom", 
        dy: -5,
        dx: 35
        }))
    ],
    color: {
        domain: ["residential", "commercial", "other"],
        range: ["#0084c1", "#e29617", "#fad900"]
    }
})


```

## Railbelt

@fig-price-sector-railbelt shows the average price of electricity in the Railbelt region for each customer class and each year of the report. Between 2011 and 2019, Other customers saw a large decrease in price, followed by a gradual increase. Residential and Commercial customers experienced slight decreases in price until 2013 when prices reversed and rose dramatically. 

The average real price of electricity for Residential customers in the Railbelt rose `{ojs} railbelt_res_change`% from `{ojs} railbelt_res_2011` cents/kWh in 2011 to `{ojs} railbelt_res_2019` cents/kWh in 2019. The average price of electricity for Commercial customers in the Railbelt rose `{ojs} railbelt_com_change`% from `{ojs} railbelt_com_2011` cents/kWh in 2011 to `{ojs} railbelt_com_2019` cents/kWh in 2019. Finally, the average price of electricity for Other customers in the Railbelt fell `{ojs} railbelt_other_change`% from `{ojs} railbelt_other_2011` cents/kWh in 2011 to `{ojs} railbelt_other_2019` cents/kWh in 2019.  

This region differs significantly from the Coastal and Rural Remote regions in that residential customers pay more for electricity than the Commercial or Other customer classes.

```{ojs}
// aggregate
railbelt_weighted_prices = tidy(weighted_prices, 
                              filter((d) => d.acep_energy_region === "Railbelt"),
                              filter((d) => d.year < 2020)
                            ).map((d) => ({...d, "Customer Class": d.sector}))
```

```{ojs}
//| label: fig-price-sector-railbelt
//| fig-cap: "Sector Price Over Time, Railbelt Region"

// plot of regional average prices
Plot.plot({

    // Configure the x-axis
    x: {
      domain: [2011, 2019],
      tickFormat: "d",
      label: "Year"
    },
    
    // Configure the y-axis
    y: {
      domain: [10, 40],
      ticks: 4,
      label: "Cents per Kilowatt Hour"
    },
    
    // Configure the plot
    grid: true,
    marginRight: 70,
  width: width,


    marks: [

    Plot.line(railbelt_weighted_prices,
        {x: "year", 
        y: "weighted_price",
        strokeWidth: 5,
        stroke: "Customer Class",
        tip: {format: {x: "d"}}
        }),
    Plot.text(railbelt_weighted_prices, 
      Plot.selectLast(
        {x: "year", 
        y: "weighted_price", 
        z: "Customer Class",
        text: "Customer Class", 
        frameAnchor: "bottom", 
        dy: -5,
        dx: 35
        }))
    ],
    color: {
        domain: ["residential", "commercial", "other"],
        range: ["#0084c1", "#e29617", "#fad900"]
    }
})


```

## Rural Remote
@fig-price-sector-rural shows the average price of electricity in the Rural Remote region for each customer class and year of the report. Between 2011 and 2019, Residential customers experienced a gradual increase in rates, while Commercial and Other customers experienced a gradual decrease in rates. 

The average price of electricity for the Residential customers in the Rural Remote region rose `{ojs} rural_res_change`% from `{ojs} rural_res_2011` cents/kWh in 2011 to `{ojs} rural_res_2019` cents/kWh in 2019. The average price of electricity for Commercial customers in the Rural Remote region fell `{ojs} rural_com_change`% from `{ojs} rural_com_2011` cents/kWh in 2011 to `{ojs} rural_com_2019` cents/kWh in 2019. Finally, the average price of electricity for Other customers in the Rural Remote region fell `{ojs} rural_other_change`% from `{ojs} rural_other_2011` cents/kWh in 2011 to `{ojs} rural_other_2019` cents/kWh in 2019.

```{ojs}
// aggregate
rural_remote_weighted_prices = tidy(weighted_prices, 
                              filter((d) => d.acep_energy_region === "Rural Remote"),
                              filter((d) => d.year < 2020)
                            ).map((d) => ({...d, "Customer Class": d.sector}))
```

```{ojs}
//| label: fig-price-sector-rural
//| fig-cap: "Sector Price Over Time, Rural Remote Region"

// plot of regional average prices
Plot.plot({
    
    // Configure the x-axis
    x: {
      domain: [2011, 2019],
      tickFormat: "d",
      label: "Year"
    },
  
    // Configure the y-axis
    y: {
      domain: [10, 70],
      ticks: 7,
      label: "Cents per Kilowatt Hour"
    },
    
    // Configure the plot
    grid: true,
    marginRight: 70,
    height: 700,
  width: width,

    marks: [
 
      Plot.line(rural_remote_weighted_prices,
          {x: "year", 
          y: "weighted_price",
          strokeWidth: 5,
          stroke: "Customer Class",
          tip: {format: {x: "d"}}
          }),
      Plot.text(rural_remote_weighted_prices, 
        Plot.selectLast(
          {x: "year", 
          y: "weighted_price", 
          z: "Customer Class",
          text: "Customer Class", 
          frameAnchor: "bottom", 
          dy: -5,
          dx: 35
          }))
    ],
    color: {
        domain: ["residential", "commercial", "other"],
        range: ["#0084c1", "#e29617", "#fad900"]
    }
})


```



```{ojs}
// price extraction function

function extract_price(region, year, sector) {
  const filteredData = weighted_prices.filter(
    d => d.year === year && 
    d.sector === sector &&
    d.acep_energy_region === region);

  const extractedPrice = Math.round(filteredData.map(d => d.weighted_price));

  return extractedPrice;
};

```

```{ojs}
// percentage function

function percent_change(region, start_year, end_year, sector){
  const start_price = extract_price(region, start_year, sector);
  const end_price = extract_price(region, end_year, sector);

  const rawPercent = (((start_price - end_price)/start_price) * 100);
  const percent = Math.abs(Math.round(rawPercent));

  return percent;
} 

```

```{ojs}
// starting prices

rural_res_2011 = extract_price("Rural Remote", 2011, 'residential');
railbelt_res_2011 = extract_price("Railbelt", 2011, 'residential');
coastal_res_2011 = extract_price("Coastal", 2011, 'residential');

rural_com_2011 = extract_price("Rural Remote", 2011, 'commercial');
railbelt_com_2011 = extract_price("Railbelt", 2011, 'commercial');
coastal_com_2011 = extract_price("Coastal", 2011, 'commercial');

rural_other_2011 = extract_price("Rural Remote", 2011, 'other');
railbelt_other_2011 = extract_price("Railbelt", 2011, 'other');
coastal_other_2011 = extract_price("Coastal", 2011, 'other');

```

```{ojs}
// ending prices

rural_res_2019 = extract_price("Rural Remote", 2019, 'residential');
railbelt_res_2019 = extract_price("Railbelt", 2019, 'residential');
coastal_res_2019 = extract_price("Coastal", 2019, 'residential');

rural_com_2019 = extract_price("Rural Remote", 2019, 'commercial');
railbelt_com_2019 = extract_price("Railbelt", 2019, 'commercial');
coastal_com_2019 = extract_price("Coastal", 2019, 'commercial');

rural_other_2019 = extract_price("Rural Remote", 2019, 'other');
railbelt_other_2019 = extract_price("Railbelt", 2019, 'other');
coastal_other_2019 = extract_price("Coastal", 2019, 'other');

```

```{ojs}
// percent changes

coastal_res_change = percent_change("Coastal", 2011, 2019, 'residential');
coastal_com_change = percent_change("Coastal", 2011, 2019, 'commercial');
coastal_other_change = percent_change("Coastal", 2011, 2019, 'other');

railbelt_res_change = percent_change("Railbelt", 2011, 2019, 'residential');
railbelt_com_change = percent_change("Railbelt", 2011, 2019, 'commercial');
railbelt_other_change = percent_change("Railbelt", 2011, 2019, 'other');

rural_res_change = percent_change("Rural Remote", 2011, 2019, 'residential');
rural_com_change = percent_change("Rural Remote", 2011, 2019, 'commercial');
rural_other_change = percent_change("Rural Remote", 2011, 2019, 'other');

```


```{ojs}
// load libraries
stdlib = require("@observablehq/stdlib")
d3 = require("d3@7")
import {tidy, groupBy, rename, summarize, sum, mutate, select, n, nDistinct, mean, filter, pivotWider, pivotLonger, leftJoin, slice} from "@pbeshai/tidyjs"

// load data
prices = FileAttachment("data/working/prices/prices.csv").csv({typed: true});
weighted_prices = FileAttachment("data/working/prices/weighted_prices.csv").csv({typed: true});

```